modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "betterfly"
version = "${version}"
displayName = "BetterFly"
authors = "TYX_CnJiu"
description = '''
It's a flight mod
Players can type
/flying
to enable or disable the flying.
'''
#logoFile = ""

[[dependencies.betterfly]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterfly]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterfly]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "untitled2.mixins.json"
